import type { GlassPicks } from "./variants";

// App-wide per-mode glass defaults — Ellis's Design Lab picks, applied as the
// baseline look for every user (overridable per-account via the Design Lab).
//
// Fallback order in usePickForCard:
//   user's own pick  →  DEFAULT_PICKS  →  GlassCard's defaultVariant prop  →  v00
// so an entry here overrides the component's hardcoded defaultVariant.
//
// A glassId with no matching GlassCard on screen is simply inert. Grows as
// Ellis sends more pages of picks. Typed as GlassPicks so every id is
// compile-checked against the variant catalog. 2026-08-10.
export const DEFAULT_PICKS: GlassPicks = {
  "hub-wins": { light: "v05", dark: "v05" },
  "todo-main": { light: "v05", dark: "v05" },
  "nav-topbar": { light: "v19", dark: "v19" },
  "nav-sidebar": { light: "v19", dark: "v19" },
  "updates-day": { light: "v05", dark: "v05" },
  "sidebar-fees": { light: "v06", dark: "v05" },
  "contacts-card": { light: "v05", dark: "v04" },
  "hub-attention": { light: "v28", dark: "v05" },
  "hub-diary": { light: "v27", dark: "v11" },
  "myfiles-table": { light: "v05", dark: "v05" },
  "overview-risk": { light: "v05", dark: "v05" },
  "property-hero": { light: "v08", dark: "v04" },
  "sidebar-agent": { light: "v06", dark: "v05" },
  "steps-section": { light: "v05", dark: "v05" },
  "todo-internal": { light: "v05", dark: "v05" },
  "myfiles-search": { light: "v25", dark: "v07" },
  "overview-notes": { light: "v23", dark: "v11" },
  "steps-progress": { light: "v05", dark: "v05" },
  "auto-emails-row": { light: "v08", dark: "v05" },
  "reminders-group": { light: "v05", dark: "v05" },
  "todo-page-group": { light: "v05", dark: "v05" },
  "updates-tx-card": { light: "v16", dark: "v02" },
  "hub-service-split": { light: "v05", dark: "v05" },
  "sidebar-key-dates": { light: "v06", dark: "v05" },
  "milestone-timeline": { light: "v29", dark: "v26" },
  "overview-reminders": { light: "v04", dark: "v04" },
  "steps-not-required": { light: "v05", dark: "v10" },
  "analytics-list-card": { light: "v05", dark: "v05" },
  "analytics-stat-card": { light: "v05", dark: "v26" },
  "analytics-counts": { dark: "v14" },
  "hub-activity-ribbon": { light: "v05", dark: "v05" },
  "hub-pipeline-glance": { light: "v26", dark: "v14" },
  "hub-pipeline-health": { light: "v05", dark: "v05" },
  "overview-ai-summary": { light: "v27", dark: "v05" },
  "overview-solicitors": { light: "v05", dark: "v05" },
  "reminders-completed": { light: "v05", dark: "v05" },
  "reminders-file-card": { light: "v05", dark: "v05" },
  "sidebar-quick-links": { light: "v06", dark: "v05" },
  "sidebar-sale-health": { light: "v06", dark: "v05" },
  "todo-agent-requests": { light: "v05", dark: "v05" },
  "activity-comms-entry": { light: "v22", dark: "v22" },
  "overview-next-action": { light: "v18", dark: "v07" },
  "reminders-filter-bar": { light: "v06", dark: "v19" },
  "hub-exchange-forecast": { light: "v05", dark: "v05" },
  "activity-compose-email": { light: "v08", dark: "v08" },
  "reminders-alerts-strip": { light: "v27", dark: "v25" },
  "overview-property-intel": { light: "v05", dark: "v05" },
  "overview-recent-activity": { light: "v05", dark: "v05" },
  "reminders-automated-emails": { light: "v22", dark: "v22" },
  "contacts-person": { light: "v03", dark: "v04" },
  "new-sale-drop-memo": { light: "v26", dark: "v16" },
  "new-sale-research": { light: "v05", dark: "v05" },
  "new-sale-sold-prices": { light: "v05", dark: "v05" },
  "new-sale-hero": { light: "v08", dark: "v04" },
  "new-sale-portal-invite": { light: "v15", dark: "v15" },
  "new-sale-vendors": { light: "v05", dark: "v04" },
  "new-sale-purchasers": { light: "v05", dark: "v04" },
  "new-sale-solicitors": { light: "v05", dark: "v04" },
  "new-sale-chain": { light: "v28", dark: "v28" },
  "new-sale-file-worth": { light: "v06", dark: "v07" },
  "new-sale-notes": { light: "v06", dark: "v04" },

  // Onboarding empty states (Hub / Completions / To-Do / Updates / All Files /
  // Analytics). Mostly dark-only picks — light stays v00 baseline. 2026-08-31.
  "empty-hub-place": { dark: "v04" },
  "empty-hub-attention": { dark: "v04" },
  "empty-hub-picture": { dark: "v04" },
  "empty-hub-finish": { light: "v20", dark: "v19" },
  "hub-email-nudge": { light: "v25", dark: "v21" },
  "empty-completions-profile": { dark: "v04" },
  "empty-completions-agency": { dark: "v04" },
  "empty-completions-invite": { dark: "v04" },
  "empty-todo-notes": { dark: "v04" },
  "empty-todo-sale": { dark: "v04" },
  // Not in Ellis's export (only shows for outsourced agencies) — matched to its
  // two sibling cards so the row is consistent. 2026-08-31.
  "empty-todo-progressor": { dark: "v04" },
  "empty-updates-solicitor": { dark: "v04" },
  "empty-updates-progress": { dark: "v04" },
  "empty-updates-confirmed": { dark: "v04" },
  "empty-allfiles-demo": { light: "v25", dark: "v21" },
  "empty-allfiles-risk": { dark: "v04" },
  "empty-allfiles-next": { dark: "v04" },
  "empty-allfiles-exchange": { dark: "v04" },
  "empty-analytics-solicitors": { dark: "v04" },
  "empty-analytics-commission": { dark: "v04" },
  "empty-analytics-conversion": { dark: "v04" },
  "empty-partners-broker": { dark: "v04" },
  "empty-partners-solicitor": { dark: "v04" },
  "empty-partners-network": { dark: "v04" },
  // Mirrors the All Files "finished example" card.
  "empty-partners-nosales": { light: "v25", dark: "v21" },
};
