import Link from "next/link";

export const metadata = { title: "Terms of Service — The Sales Progressor" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-8">
          <Link href="/login" className="text-sm text-blue-600 hover:text-blue-700">← Back to login</Link>
        </div>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: April 2026</p>

        <div className="prose prose-slate max-w-none space-y-8">

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">1. About this service</h2>
            <p className="text-slate-600 leading-relaxed">The Sales Progressor is a property transaction management platform operated by The Sales Progressor Ltd. It is provided to estate agencies and property professionals to help manage and communicate progress on residential property sales.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">2. Access and accounts</h2>
            <p className="text-slate-600 leading-relaxed">Access to the platform is granted by invitation or registration. You are responsible for maintaining the security of your account credentials. You must not share your login with others or use another person's account.</p>
            <p className="text-slate-600 leading-relaxed mt-3">Portal access links sent to buyers and sellers are personal and should not be shared or forwarded. Each link is tied to an individual's record on a specific transaction.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">3. Acceptable use</h2>
            <p className="text-slate-600 leading-relaxed">You agree to use the platform only for its intended purpose of property transaction management and progression. You must not use the platform to send unsolicited messages, transmit harmful content, attempt to access data you are not authorised to view, or interfere with the platform's operation.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">4. Data and communications</h2>
            <p className="text-slate-600 leading-relaxed">Communications sent through the platform (emails, WhatsApp messages, notes) are logged for record-keeping and compliance purposes. By using the platform, you consent to this logging. Messages sent to buyers and sellers via the chase or comms features are the responsibility of the sending user.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">5. AI-generated content</h2>
            <p className="text-slate-600 leading-relaxed">The platform includes AI-assisted message generation. Any messages generated by AI are drafts for review — you are responsible for reviewing and approving any AI-generated content before it is sent. The Sales Progressor accepts no liability for AI-generated content that is sent without appropriate review.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">6. Availability and limitation of liability</h2>
            <p className="text-slate-600 leading-relaxed">We aim to provide a reliable service but cannot guarantee uninterrupted availability. The Sales Progressor is a communication and tracking tool — it does not provide legal, financial, or conveyancing advice. Any decisions made based on information in the platform remain the responsibility of the user and their clients.</p>
            <p className="text-slate-600 leading-relaxed mt-3">To the maximum extent permitted by law, The Sales Progressor Ltd shall not be liable for any indirect or consequential loss arising from use of the platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">7. Changes to these terms</h2>
            <p className="text-slate-600 leading-relaxed">We may update these terms from time to time. Continued use of the platform after changes are published constitutes acceptance of the updated terms. We will notify registered users of material changes by email.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">8. Contact</h2>
            <p className="text-slate-600 leading-relaxed">Questions about these terms: <a href="mailto:hello@thesalesprogressor.co.uk" className="text-blue-600 hover:text-blue-700">hello@thesalesprogressor.co.uk</a></p>
          </section>

        </div>
      </div>
    </div>
  );
}
