// Client-facing copy for portal milestone display
// Labels and descriptions written from the buyer/seller's perspective

export type PortalCopy = {
  label: string;
  labelOther?: string;  // third-person version shown when the other party views this milestone
  who: "you" | "solicitor" | "agent" | "lender";
  typicalDuration?: string;
  description?: string;
};

const copy: Record<string, PortalCopy> = {
  // ── Vendor milestones ────────────────────────────────────────────────────
  VM1:  { label: "Instruct your solicitor",                  labelOther: "Seller instructed their solicitor",         who: "you",
    description: "You need to formally appoint a solicitor to handle the legal side of your sale. Contact them directly to confirm you're instructing them — they'll then begin preparing the paperwork." },
  VM2:  { label: "Receive memorandum of sale",               who: "solicitor",
    description: "Your estate agent sends a memorandum of sale to all solicitors confirming the agreed price, buyer details, and any special conditions. This officially kicks off the legal process." },
  VM3:  { label: "Receive welcome pack from solicitor",      labelOther: "Seller received welcome pack from solicitor", who: "you",
    description: "Your solicitor sends you a welcome pack containing their terms of business, a questionnaire, and ID requirements. Return it promptly — delays here slow down the whole transaction." },
  VM14: { label: "Complete ID & AML checks",                 labelOther: "Seller completed ID & AML checks",           who: "you",
    description: "Anti-money laundering law requires your solicitor to verify your identity. You'll need a passport or driving licence, plus a recent utility bill or bank statement. This is a legal requirement." },
  VM15: { label: "Receive property information forms",       labelOther: "Seller received property information forms",  who: "you",
    description: "Your solicitor will send you property information forms (TA6 and TA10) asking about the property — fixtures included in the sale, disputes, planning consents, and more. Complete these carefully and honestly." },
  VM4:  { label: "Return completed property forms",          labelOther: "Seller returned completed property forms",   who: "you",
    description: "Once you've filled in the property information forms, return them to your solicitor. These are sent to the buyer's solicitor as part of the contract pack." },
  VM5:  { label: "Draft contract pack issued",               who: "solicitor",
    description: "Your solicitor sends the draft contract pack to the buyer's solicitor. This includes the contract, property information forms, title documents, and any relevant certificates." },
  VM6:  { label: "Management pack requested",                who: "solicitor",
    description: "If the property is leasehold or share of freehold, your solicitor requests a management pack from the freeholder or managing agent. This contains details about service charges, ground rent, and building insurance." },
  VM7:  { label: "Management pack received",                 who: "solicitor", typicalDuration: "can take 4–8 weeks",
    description: "The management pack has arrived from the freeholder or managing agent. These often take weeks to arrive and are one of the most common causes of delays in leasehold transactions." },
  VM16: { label: "Initial enquiries received",               who: "solicitor",
    description: "The buyer's solicitor has raised questions about the property — these might cover planning history, building works, boundaries, or anything in the documents that needs clarification." },
  VM17: { label: "Provide replies to enquiries",             labelOther: "Seller provided replies to enquiries",      who: "you",
    description: "Your solicitor needs your input to answer some of the buyer's questions. Respond as quickly as you can — delays in enquiries are one of the most common reasons transactions stall." },
  VM8:  { label: "Replies sent to buyer's solicitor",        who: "solicitor",
    description: "Your solicitor has sent replies to the buyer's enquiries. The buyer's solicitor will review these and may raise further questions." },
  VM18: { label: "Additional enquiries received",            who: "solicitor",
    description: "A second round of questions has arrived from the buyer's solicitor. This is completely normal — most transactions have at least two rounds of enquiries." },
  VM19: { label: "Provide additional replies",               labelOther: "Seller provided additional replies",         who: "you",
    description: "Your solicitor needs your help with another set of questions from the buyer. Answer them as soon as possible to keep the transaction moving." },
  VM9:  { label: "Additional replies sent",                  who: "solicitor",
    description: "Your solicitor has replied to the additional enquiries. Once both solicitors are satisfied, you're moving towards exchange." },
  VM10: { label: "Contract documents issued to you",         labelOther: "Contract documents issued to seller",       who: "you",
    description: "Your solicitor has sent you the final contract to review and sign. Read it carefully — check the price, completion date, and what's included in the sale." },
  VM11: { label: "Sign and return contract documents",       labelOther: "Seller signed and returned contract",       who: "you",
    description: "Sign the contract documents and return them to your solicitor. The contracts aren't exchanged yet — you're signing them ready for exchange, which is the legally binding moment." },
  VM20: { label: "Solicitor confirms ready to exchange",     who: "solicitor", typicalDuration: "typically 1–5 days after signing",
    description: "Your solicitor has confirmed they have everything in place to exchange contracts. Once both sides are ready, your agent will coordinate the exchange." },
  VM12: { label: "Contracts exchanged",                      who: "agent",
    description: "Exchange is the legally binding moment of your sale. Both solicitors formally exchange signed contracts. Neither side can now withdraw without significant financial penalty. The completion date is now fixed." },
  VM13: { label: "Sale completed",                           who: "agent",
    description: "The sale is complete. Your solicitor has received the purchase funds, redeemed your mortgage, and transferred ownership. Leave the keys and any agreed items at the property." },

  // ── Purchaser milestones ─────────────────────────────────────────────────
  PM1:  { label: "Instruct your solicitor",                  labelOther: "Buyer instructed their solicitor",          who: "you",
    description: "Formally appoint a solicitor to handle the conveyancing for your purchase. Contact them to confirm you're instructing them — they'll send you a welcome pack and start work." },
  PM2:  { label: "Receive memorandum of sale",               who: "solicitor",
    description: "The estate agent sends a memorandum of sale to all solicitors confirming the agreed price and parties. This officially starts the legal process on both sides." },
  PM14a:{ label: "Complete ID & AML checks",                 labelOther: "Buyer completed ID & AML checks",           who: "you",
    description: "Anti-money laundering regulations require your solicitor to verify your identity before they can act for you. You'll need a photo ID and a recent proof of address." },
  PM15a:{ label: "Pay money on account to solicitor",        labelOther: "Buyer paid money on account to solicitor",  who: "you",
    description: "Your solicitor will ask for an initial payment to cover the cost of searches and disbursements. This is separate from the deposit and is typically a few hundred pounds." },
  PM4:  { label: "Submit mortgage application",              labelOther: "Buyer submitted mortgage application",      who: "you",
    description: "If you're buying with a mortgage, submit your full mortgage application to your lender. Your broker can do this on your behalf. Your agreement in principle needs to be converted into a full application." },
  PM5:  { label: "Lender valuation booked",                  who: "lender", typicalDuration: "usually 1–2 weeks after application",
    description: "Your mortgage lender has booked a valuation of the property to confirm it's worth what you're paying. This is not a structural survey — it's for the lender's benefit, not yours. Consider booking your own survey separately." },
  PM3:  { label: "Draft contract pack received",             who: "solicitor",
    description: "Your solicitor has received the contract pack from the seller's solicitor. This includes the draft contract, title documents, and property information forms. Your solicitor will review everything carefully." },
  PM9:  { label: "Searches ordered",                         who: "solicitor", typicalDuration: "results in 2–6 weeks",
    description: "Your solicitor has applied for searches — checks with the local council, water authority, and other bodies. These reveal planning permissions, flood risk, drainage, and other factors affecting the property." },
  PM7:  { label: "Book your survey",                         labelOther: "Buyer booked their survey",                 who: "you",
    description: "Consider booking an independent structural survey. A RICS HomeBuyer Report (Level 2) costs around £400–700 and can identify issues that save you money — or give you negotiating leverage on the price." },
  PM20: { label: "Survey report received",                   who: "you",
    description: "Your surveyor has delivered their report. Read it carefully. Most reports flag some issues — many are minor. If anything significant is raised, discuss it with your solicitor and consider renegotiating the price." },
  PM6:  { label: "Mortgage offer received",                  who: "lender", typicalDuration: "typically 1–3 weeks after valuation",
    description: "Your mortgage lender has formally offered you the loan. Check the amount, interest rate, term, and any conditions. Your solicitor will receive a copy — they'll need to check it against the property title." },
  PM8:  { label: "Management pack received",                 who: "solicitor",
    description: "If the property is leasehold, the management pack from the freeholder or managing agent has arrived. Your solicitor will review service charge accounts, ground rent, building insurance, and any planned major works." },
  PM10: { label: "Search results received",                  who: "solicitor", typicalDuration: "usually 2–6 weeks",
    description: "The search results have come back from the local authority and other bodies. Your solicitor will review them and flag anything that needs attention or further investigation." },
  PM11: { label: "Initial enquiries raised",                 who: "solicitor",
    description: "Your solicitor has sent questions to the seller's solicitor about the property. This is a normal part of the process — they're checking everything is in order before you exchange." },
  PM21: { label: "Initial replies received",                 who: "solicitor",
    description: "The seller's solicitor has replied to your solicitor's questions. Your solicitor will review the answers and decide whether further questions are needed." },
  PM22: { label: "Initial replies reviewed",                 who: "solicitor",
    description: "Your solicitor has reviewed the replies to their enquiries. They may raise further questions, or they may be satisfied and move towards exchange." },
  PM12: { label: "Additional enquiries raised",              who: "solicitor",
    description: "Your solicitor has raised a second round of questions. This is completely normal — most transactions go through two or three rounds of enquiries before all points are resolved." },
  PM23: { label: "Additional replies received",              who: "solicitor",
    description: "Replies to the additional enquiries have arrived from the seller's solicitor. Your solicitor will review them." },
  PM24: { label: "Additional replies reviewed",              who: "solicitor",
    description: "Your solicitor has reviewed all outstanding replies. They should now have everything they need to report to you and move towards exchange." },
  PM25: { label: "All enquiries satisfied",                  who: "solicitor",
    description: "All legal questions about the property have been answered to your solicitor's satisfaction. This is a significant milestone — you're now in the final stretch before exchange." },
  PM26: { label: "Final report received from solicitor",     who: "you",
    description: "Your solicitor has sent you their final report summarising everything about the property, the title, the searches, and any conditions on your mortgage offer. Read it and raise any questions before signing." },
  PM13: { label: "Contract documents issued to you",         labelOther: "Contract documents issued to buyer",        who: "you",
    description: "Your solicitor has sent you the contract to review and sign. Check the price, completion date, and included fixtures. Signing doesn't commit you yet — that happens at exchange." },
  PM14b:{ label: "Sign and return contract documents",       labelOther: "Buyer signed and returned contract",        who: "you",
    description: "Sign the contract and return it to your solicitor. They'll hold it ready for exchange. Make sure you're happy with the completion date before signing." },
  PM15b:{ label: "Transfer the deposit",                     labelOther: "Buyer transferred the deposit",             who: "you",
    description: "Transfer your deposit — typically 10% of the purchase price — to your solicitor's client account. It must be cleared funds before exchange can happen. Allow a few days for bank transfers." },
  PM27: { label: "Solicitor confirms ready to exchange",     who: "solicitor", typicalDuration: "typically 1–5 days after signing",
    description: "Your solicitor has confirmed they have everything they need to exchange. Your agent is now coordinating with the seller's side to agree a date and time." },
  PM16: { label: "Contracts exchanged",                      who: "agent",
    description: "Exchange is the legally binding moment of your purchase. Both solicitors exchange signed contracts and your deposit is transferred. The completion date is now fixed and neither side can withdraw without financial penalty." },
  PM17: { label: "Purchase completed",                       who: "agent",
    description: "The purchase is complete. Your solicitor has received the title deeds and will register your ownership at HM Land Registry. The keys are yours — welcome home." },
};

export function getMilestoneCopy(code: string): PortalCopy {
  return copy[code] ?? { label: code, who: "solicitor" };
}

export const WHO_LABELS: Record<string, string> = {
  you:       "You",
  solicitor: "Your solicitor",
  agent:     "Your agent",
  lender:    "Your lender",
};
