// Daily founder brief — generated by Claude Haiku, sent via SendGrid.
// Primary channel: email to ellisaskey+founder-brief@googlemail.com (CLARIFICATION 3).
// Secondary: OutboundMessage row as audit record.
// Confidence thresholds (ADMIN_07 §5.2):
//   ≥0.8 → headline, 0.5–0.8 → body, 0.2–0.5 → worth watching, <0.2 → suppressed.

import { prisma } from "@/lib/prisma";
import { anthropic } from "@/lib/anthropic";
import { sendEmail } from "@/lib/email";
import type { Signal } from "@prisma/client";

const FOUNDER_BRIEF_EMAIL = "ellisaskey+founder-brief@googlemail.com";
const HAIKU_MODEL = "claude-haiku-4-5-20251001";
const LOOKBACK_HOURS = 28; // slightly past 24h so midnight runs don't miss anything

function classifySignals(signals: Signal[]): {
  headline: Signal[];
  body: Signal[];
  watching: Signal[];
} {
  return {
    headline: signals.filter((s) => s.confidence >= 0.8),
    body: signals.filter((s) => s.confidence >= 0.5 && s.confidence < 0.8),
    watching: signals.filter((s) => s.confidence >= 0.2 && s.confidence < 0.5),
  };
}

function formatSignalForPrompt(s: Signal): string {
  const payload = s.payload as Record<string, unknown>;
  const lines = [
    `[${s.severity.toUpperCase()}] ${s.detectorName} (confidence: ${Math.round(s.confidence * 100)}%)`,
  ];
  for (const [k, v] of Object.entries(payload)) {
    if (k === "dedupeKey") continue;
    lines.push(`  ${k}: ${typeof v === "object" ? JSON.stringify(v) : v}`);
  }
  return lines.join("\n");
}

function buildPrompt(
  classified: ReturnType<typeof classifySignals>,
  date: string
): string {
  const sections: string[] = [];

  if (classified.headline.length > 0) {
    sections.push(
      "=== HEADLINE SIGNALS (confidence ≥80%) ===\n" +
        classified.headline.map(formatSignalForPrompt).join("\n\n")
    );
  }
  if (classified.body.length > 0) {
    sections.push(
      "=== NOTABLE SIGNALS (50–80%) ===\n" +
        classified.body.map(formatSignalForPrompt).join("\n\n")
    );
  }
  if (classified.watching.length > 0) {
    sections.push(
      "=== WORTH WATCHING (20–50%) ===\n" +
        classified.watching.map(formatSignalForPrompt).join("\n\n")
    );
  }

  if (sections.length === 0) {
    return `Date: ${date}\n\nNo signals above confidence threshold today. All systems normal.`;
  }

  return `Date: ${date}\n\n${sections.join("\n\n")}`;
}

async function generateBriefText(signalSummary: string): Promise<string> {
  const systemPrompt = `You are an AI assistant writing a concise daily operational brief for the founder of Sales Progressor, a UK property transaction SaaS. Write in plain text (no markdown). Be direct and actionable. Format:

1. ONE-LINE SUMMARY (what matters most today)
2. KEY SIGNALS (bullet points, one per signal group — ignore worth-watching unless it's the only content)
3. SUGGESTED ACTION (1–2 specific things to do today, if signals warrant it)

Keep the total under 250 words. Use plain business English, no jargon.`;

  const msg = await anthropic.messages.create({
    model: HAIKU_MODEL,
    max_tokens: 400,
    system: systemPrompt,
    messages: [{ role: "user", content: signalSummary }],
  });

  const block = msg.content[0];
  if (block.type !== "text") throw new Error("Unexpected Claude response type");
  return block.text.trim();
}

export async function runDailyBrief(now: Date = new Date()): Promise<{ sent: boolean; signalCount: number }> {
  const since = new Date(now.getTime() - LOOKBACK_HOURS * 60 * 60 * 1000);

  const signals = await prisma.signal.findMany({
    where: {
      detectedAt: { gte: since },
      confidence: { gte: 0.2 },
    },
    orderBy: [{ confidence: "desc" }, { detectedAt: "desc" }],
  });

  const dateStr = now.toLocaleDateString("en-GB", {
    timeZone: "Europe/London",
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const classified = classifySignals(signals);
  const signalSummary = buildPrompt(classified, dateStr);
  const briefText = await generateBriefText(signalSummary);

  const subject = `Founder Brief — ${dateStr}`;

  // Primary: send email
  await sendEmail({
    to: FOUNDER_BRIEF_EMAIL,
    subject,
    text: briefText,
  });

  // Secondary: audit record in OutboundMessage
  await prisma.outboundMessage.create({
    data: {
      type: "internal_note",
      channel: "email",
      purpose: "digest",
      status: "sent",
      recipientEmail: FOUNDER_BRIEF_EMAIL,
      subject,
      content: briefText,
      wasAiGenerated: true,
      aiModel: HAIKU_MODEL,
    },
  });

  return { sent: true, signalCount: signals.length };
}
