// Daily founder brief — generated by Claude Haiku, sent via SendGrid.
// Primary channel: email to ellisaskey+founder-brief@googlemail.com.
// Secondary: OutboundMessage row as audit record.
//
// Now grounded in REAL numbers (this week vs last week) plus a live operational
// snapshot and the de-duplicated active signals — see buildInsightContext.

import { prisma } from "@/lib/prisma";
import { anthropic } from "@/lib/anthropic";
import { sendEmail } from "@/lib/email";
import { buildInsightContext } from "./context";

const FOUNDER_BRIEF_EMAIL = "ellisaskey+founder-brief@googlemail.com";
const HAIKU_MODEL = "claude-haiku-4-5-20251001";

async function generateBriefText(contextText: string): Promise<string> {
  const systemPrompt = `You are an AI assistant writing a concise daily operational brief for the founder of Sales Progressor, a UK property transaction SaaS. Write in plain text (no markdown, no em-dashes). Be direct and specific — quote the real numbers you are given.

Format:
1. ONE-LINE SUMMARY (what matters most today)
2. KEY MOVEMENTS (bullets — the metric changes that matter, with the actual figures)
3. NEEDS ATTENTION (bullets — the open situations from the snapshot/signals worth acting on today)
4. SUGGESTED ACTION (1-2 specific things to do today)

Keep the total under 250 words. Plain business English. If a number did not really move, do not dramatise it.`;

  const msg = await anthropic.messages.create({
    model: HAIKU_MODEL,
    max_tokens: 500,
    system: systemPrompt,
    messages: [{ role: "user", content: contextText }],
  });

  const block = msg.content[0];
  if (block.type !== "text") throw new Error("Unexpected Claude response type");
  return block.text.trim();
}

export async function runDailyBrief(now: Date = new Date()): Promise<{ sent: boolean; signalCount: number }> {
  const { contextText, activeSignals } = await buildInsightContext(now);

  const dateStr = now.toLocaleDateString("en-GB", {
    timeZone: "Europe/London",
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const briefText = await generateBriefText(`Date: ${dateStr}\n\n${contextText}`);
  const subject = `Founder Brief — ${dateStr}`;

  await sendEmail({ to: FOUNDER_BRIEF_EMAIL, subject, text: briefText });

  await prisma.outboundMessage.create({
    data: {
      type: "internal_note",
      channel: "email",
      purpose: "digest",
      status: "sent",
      recipientEmail: FOUNDER_BRIEF_EMAIL,
      subject,
      content: briefText,
      wasAiGenerated: true,
      aiModel: HAIKU_MODEL,
    },
  });

  return { sent: true, signalCount: activeSignals.length };
}
