// Weekly founder review — generated by Claude Opus 4.7 (CLARIFICATION 2), sent via SendGrid.
// Runs Monday morning. Covers signals from the past 7 days plus active experiments.
// Primary channel: email to ellisaskey+founder-brief@googlemail.com.
// Secondary: OutboundMessage audit record.

import { prisma } from "@/lib/prisma";
import { anthropic } from "@/lib/anthropic";
import { sendEmail } from "@/lib/email";
import type { Signal } from "@prisma/client";

const FOUNDER_BRIEF_EMAIL = "ellisaskey+founder-brief@googlemail.com";
const OPUS_MODEL = "claude-opus-4-7";
const LOOKBACK_DAYS = 7;

function formatSignal(s: Signal): string {
  const payload = s.payload as Record<string, unknown>;
  const lines = [
    `[${s.severity.toUpperCase()} | ${Math.round(s.confidence * 100)}%] ${s.detectorName}`,
  ];
  for (const [k, v] of Object.entries(payload)) {
    if (k === "dedupeKey") continue;
    lines.push(`  ${k}: ${typeof v === "object" ? JSON.stringify(v) : v}`);
  }
  return lines.join("\n");
}

export async function runWeeklyReview(now: Date = new Date()): Promise<{ sent: boolean; signalCount: number }> {
  const since = new Date(now.getTime() - LOOKBACK_DAYS * 24 * 60 * 60 * 1000);

  const [signals, experiments] = await Promise.all([
    prisma.signal.findMany({
      where: {
        detectedAt: { gte: since },
        confidence: { gte: 0.2 },
      },
      orderBy: [{ confidence: "desc" }, { severity: "desc" }, { detectedAt: "desc" }],
    }),
    prisma.experiment.findMany({
      where: { status: { in: ["proposed", "active"] } },
      orderBy: { proposedAt: "desc" },
    }),
  ]);

  const weekEnding = now.toLocaleDateString("en-GB", {
    timeZone: "Europe/London",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  // Build signal section grouped by severity
  const bySeverity = {
    critical: signals.filter((s) => s.severity === "critical"),
    leak: signals.filter((s) => s.severity === "leak"),
    opportunity: signals.filter((s) => s.severity === "opportunity"),
    info: signals.filter((s) => s.severity === "info"),
  };

  const signalSection = Object.entries(bySeverity)
    .filter(([, arr]) => arr.length > 0)
    .map(([sev, arr]) => `--- ${sev.toUpperCase()} (${arr.length}) ---\n${arr.map(formatSignal).join("\n\n")}`)
    .join("\n\n");

  // Build experiment section
  const experimentSection = experiments.length === 0
    ? "No active or proposed experiments."
    : experiments
        .map((e) => [
          `[${e.status.toUpperCase()}] ${e.name}`,
          `  Hypothesis: ${e.hypothesis}`,
          `  Primary metric: ${e.primaryMetric}`,
          e.startedAt ? `  Started: ${e.startedAt.toISOString().slice(0, 10)}` : null,
          e.notes ? `  Notes: ${e.notes}` : null,
        ].filter(Boolean).join("\n"))
        .join("\n\n");

  const contextBlock = `WEEK ENDING: ${weekEnding}

=== SIGNALS (last 7 days) ===
${signalSection || "No signals above threshold this week."}

=== EXPERIMENTS ===
${experimentSection}`;

  const systemPrompt = `You are an AI analyst writing a strategic weekly review for the founder of Sales Progressor, a UK property transaction SaaS with agents and their clients as users. Write in plain text (no markdown). Be analytical, not just descriptive — connect patterns, identify root causes, and prioritise actions.

Format your response as:

WEEK IN REVIEW
[2–3 sentence narrative of the week's signal picture]

PRIORITY ACTIONS (max 5, ranked)
1. [Action — specific, owner-able, why it matters]
...

EXPERIMENTS TO CONSIDER
[Based on signals this week, suggest 1–2 hypotheses worth testing. If existing experiments are stalled, say so.]

RISKS TO WATCH
[Any signals approaching critical thresholds or patterns that could worsen]

Keep total under 500 words. Write as if briefing a founder before Monday stand-up.`;

  const msg = await anthropic.messages.create({
    model: OPUS_MODEL,
    max_tokens: 800,
    system: systemPrompt,
    messages: [{ role: "user", content: contextBlock }],
  });

  const block = msg.content[0];
  if (block.type !== "text") throw new Error("Unexpected Claude response type");
  const reviewText = block.text.trim();

  const subject = `Weekly Review — w/e ${weekEnding}`;

  await sendEmail({
    to: FOUNDER_BRIEF_EMAIL,
    subject,
    text: reviewText,
  });

  await prisma.outboundMessage.create({
    data: {
      type: "internal_note",
      channel: "email",
      purpose: "digest",
      status: "sent",
      recipientEmail: FOUNDER_BRIEF_EMAIL,
      subject,
      content: reviewText,
      wasAiGenerated: true,
      aiModel: OPUS_MODEL,
    },
  });

  return { sent: true, signalCount: signals.length };
}
