// Weekly founder review — generated by Claude Opus, sent via SendGrid.
// Runs Monday morning. Grounded in the real weekly numbers + live operational
// snapshot + de-duplicated active signals + open experiments.
// Primary channel: email to ellisaskey+founder-brief@googlemail.com.
// Secondary: OutboundMessage audit record.

import { prisma } from "@/lib/prisma";
import { anthropic } from "@/lib/anthropic";
import { sendEmail } from "@/lib/email";
import { buildInsightContext } from "./context";

const FOUNDER_BRIEF_EMAIL = "ellisaskey+founder-brief@googlemail.com";
const OPUS_MODEL = "claude-opus-4-8";

export async function runWeeklyReview(now: Date = new Date()): Promise<{ sent: boolean; signalCount: number }> {
  const [{ contextText, activeSignals }, experiments] = await Promise.all([
    buildInsightContext(now),
    prisma.experiment.findMany({
      where: { status: { in: ["proposed", "active"] } },
      orderBy: { proposedAt: "desc" },
    }),
  ]);

  const weekEnding = now.toLocaleDateString("en-GB", {
    timeZone: "Europe/London",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const experimentSection = experiments.length === 0
    ? "No active or proposed experiments."
    : experiments
        .map((e) => [
          `[${e.status.toUpperCase()}] ${e.name}`,
          `  Hypothesis: ${e.hypothesis}`,
          `  Primary metric: ${e.primaryMetric}`,
          e.startedAt ? `  Started: ${e.startedAt.toISOString().slice(0, 10)}` : null,
          e.notes ? `  Notes: ${e.notes}` : null,
        ].filter(Boolean).join("\n"))
        .join("\n\n");

  const contextBlock = `WEEK ENDING: ${weekEnding}

${contextText}

=== EXPERIMENTS ===
${experimentSection}`;

  const systemPrompt = `You are an AI analyst writing a strategic weekly review for the founder of Sales Progressor, a UK property transaction SaaS with agents and their clients as users. Write in plain text (no markdown, no em-dashes). Be analytical, not just descriptive — connect patterns, quote the real figures, identify root causes, and prioritise actions. Do not invent breadth from duplicated signals; each signal is one situation.

Format your response as:

WEEK IN REVIEW
[2-3 sentence narrative grounded in the real numbers]

PRIORITY ACTIONS (max 5, ranked)
1. [Action — specific, owner-able, why it matters]
...

EXPERIMENTS TO CONSIDER
[Based on this week, suggest 1-2 hypotheses worth testing. If existing experiments are stalled, say so.]

RISKS TO WATCH
[Open situations approaching critical, or patterns that could worsen]

Keep total under 500 words. Write as if briefing a founder before Monday stand-up.`;

  const msg = await anthropic.messages.create({
    model: OPUS_MODEL,
    max_tokens: 900,
    system: systemPrompt,
    messages: [{ role: "user", content: contextBlock }],
  });

  const block = msg.content[0];
  if (block.type !== "text") throw new Error("Unexpected Claude response type");
  const reviewText = block.text.trim();

  const subject = `Weekly Review — w/e ${weekEnding}`;

  await sendEmail({ to: FOUNDER_BRIEF_EMAIL, subject, text: reviewText });

  await prisma.outboundMessage.create({
    data: {
      type: "internal_note",
      channel: "email",
      purpose: "digest",
      status: "sent",
      recipientEmail: FOUNDER_BRIEF_EMAIL,
      subject,
      content: reviewText,
      wasAiGenerated: true,
      aiModel: OPUS_MODEL,
    },
  });

  return { sent: true, signalCount: activeSignals.length };
}
