// Walks components/ and classifies each .tsx file per the catalog rules.
// Output: docs/inventory/COMPONENTS.md.
//
// Categories:
//   - canonical            — lives in components/ui/
//   - to-extract           — domain folder, matches a known to-extract pattern
//   - domain-specific      — domain folder, no canonical equivalent
//   - outlier-grandfathered — known outlier, do not migrate without explicit instruction
//
// Re-run with: `npx tsx scripts/inventory/components.ts`
//
// Registered in docs/SCRIPTS_REGISTRY.md per Law 15. Lifetime: ongoing.
import { readdirSync, statSync, writeFileSync, readFileSync } from "fs";
import { join, relative } from "path";

const ROOT = process.cwd();
const COMPONENTS_DIR = join(ROOT, "components");
const OUTPUT = join(ROOT, "docs/inventory/COMPONENTS.md");

// Patterns from docs/reference/COMPONENT_LIBRARY_CATALOG.md §2. A component's
// filename or class usage matching one of these is a "to-extract" candidate
// when it lives outside components/ui/.
const EXTRACT_PATTERNS: Array<{ category: string; matches: (path: string, content: string) => boolean }> = [
  { category: "Card", matches: (p, c) => /Card\.tsx$/.test(p) || /glass-card/.test(c) },
  { category: "Modal", matches: (p) => /Modal\.tsx$/.test(p) },
  { category: "Banner", matches: (p) => /Banner\.tsx$/.test(p) },
  { category: "Drawer", matches: (p) => /Drawer\.tsx$/.test(p) },
  { category: "Button", matches: (_, c) => /agent-btn/.test(c) },
  { category: "Accordion", matches: (_, c) => /agent-acc-/.test(c) },
  { category: "Pill/Chip", matches: (p) => /Pill\.tsx$/.test(p) || /Chip\.tsx$/.test(p) },
  { category: "Toast", matches: (p) => /Toast\.tsx$/.test(p) },
];

// Outliers listed in the existing docs/reference/COMPONENT_LIBRARY.md
const GRANDFATHERED: string[] = [
  "components/agent/AcknowledgeButton.tsx",
  "components/agent/AgentFlagButton.tsx",
  "components/milestones/SurveyNrConfirmModal.tsx",
];

type Row = {
  path: string;
  domain: string;
  category: string;
  classification: "canonical" | "to-extract" | "domain-specific" | "outlier-grandfathered";
};

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (entry.endsWith(".tsx")) out.push(full);
  }
  return out;
}

function classify(absPath: string): Row {
  const rel = relative(ROOT, absPath).replace(/\\/g, "/");
  const segments = rel.split("/");
  const domain = segments[1] || "(root)";

  if (GRANDFATHERED.includes(rel)) {
    return { path: rel, domain, category: "outlier", classification: "outlier-grandfathered" };
  }
  if (rel.startsWith("components/ui/")) {
    return { path: rel, domain: "ui", category: "primitive", classification: "canonical" };
  }

  let content = "";
  try { content = readFileSync(absPath, "utf8"); } catch { /* skip */ }

  for (const pattern of EXTRACT_PATTERNS) {
    if (pattern.matches(rel, content)) {
      return { path: rel, domain, category: pattern.category, classification: "to-extract" };
    }
  }

  return { path: rel, domain, category: "—", classification: "domain-specific" };
}

function emit(rows: Row[]) {
  const byClass = new Map<string, Row[]>();
  for (const r of rows) {
    const arr = byClass.get(r.classification) ?? [];
    arr.push(r);
    byClass.set(r.classification, arr);
  }

  const canonical = byClass.get("canonical") ?? [];
  const toExtract = byClass.get("to-extract") ?? [];
  const domainSpecific = byClass.get("domain-specific") ?? [];
  const grandfathered = byClass.get("outlier-grandfathered") ?? [];

  // Group to-extract by category for the planning view
  const extractByCategory = new Map<string, Row[]>();
  for (const r of toExtract) {
    const arr = extractByCategory.get(r.category) ?? [];
    arr.push(r);
    extractByCategory.set(r.category, arr);
  }

  // Group domain-specific by domain
  const domainSpecByDomain = new Map<string, Row[]>();
  for (const r of domainSpecific) {
    const arr = domainSpecByDomain.get(r.domain) ?? [];
    arr.push(r);
    domainSpecByDomain.set(r.domain, arr);
  }

  const lines: string[] = [
    "# Components Census",
    "",
    `Generated by [scripts/inventory/components.ts](../../scripts/inventory/components.ts). Last run: ${new Date().toISOString().slice(0, 10)}.`,
    "",
    "Powers the [Component Library Catalog](../reference/COMPONENT_LIBRARY_CATALOG.md) and the [BUILD_PLAN Phase 2 extraction order](../BUILD_PLAN.md#phase-2--canonical-primitives--gallery-weeks-4-9).",
    "",
    "## Summary",
    "",
    `- **Total components:** ${rows.length}`,
    `- **Canonical** (in \`components/ui/\`): ${canonical.length}`,
    `- **To extract** (duplicated pattern, needs a primitive): ${toExtract.length}`,
    `- **Domain-specific** (genuinely one-of-a-kind): ${domainSpecific.length}`,
    `- **Outlier (grandfathered)** (known wrong, do not migrate): ${grandfathered.length}`,
    "",
    `Ratio canonical:bespoke = ${canonical.length}:${rows.length - canonical.length} (healthy ≈ 1:2; today ≈ 1:${Math.round((rows.length - canonical.length) / Math.max(canonical.length, 1))}).`,
    "",
    "---",
    "",
    "## Canonical (in `components/ui/`)",
    "",
  ];

  for (const r of canonical) lines.push(`- \`${r.path}\``);
  lines.push("", "---", "", "## To extract (priority view by category)", "");

  // Sort categories by count desc — biggest extraction first
  const categories = [...extractByCategory.entries()].sort((a, b) => b[1].length - a[1].length);
  for (const [cat, group] of categories) {
    lines.push(`### ${cat} (${group.length} instances)`, "");
    for (const r of group) lines.push(`- \`${r.path}\``);
    lines.push("");
  }

  lines.push("---", "", "## Domain-specific (stays in domain folder)", "");

  const domainList = [...domainSpecByDomain.entries()].sort((a, b) => b[1].length - a[1].length);
  for (const [domain, group] of domainList) {
    lines.push(`### components/${domain}/ (${group.length} files)`, "");
    for (const r of group) lines.push(`- \`${r.path}\``);
    lines.push("");
  }

  lines.push("---", "", "## Outlier (grandfathered)", "");
  for (const r of grandfathered) lines.push(`- \`${r.path}\``);
  lines.push("");

  writeFileSync(OUTPUT, lines.join("\n"));
  console.log(`Wrote ${OUTPUT}`);
  console.log(`  canonical=${canonical.length}  to-extract=${toExtract.length}  domain-specific=${domainSpecific.length}  grandfathered=${grandfathered.length}`);
}

const files = walk(COMPONENTS_DIR);
const rows = files.map(classify);
emit(rows);
