// Walks scripts/ and classifies each script per the Phase 4 cull categories.
// Output: docs/inventory/SCRIPTS.md.
//
// Categories (heuristic — manual review still required):
//   - archive-delete       — one-off audit/inspect/sweep, work done
//   - promote-feature      — should become an admin action or route
//   - promote-test         — should become a Jest unit test
//   - promote-npm-script   — keep but move to package.json scripts
//   - keep-as-is           — genuine ops tool
//
// Re-run with: `npx tsx scripts/inventory/scripts.ts`
//
// Registered in docs/SCRIPTS_REGISTRY.md per Law 15. Lifetime: ongoing.
import { readdirSync, statSync, writeFileSync, readFileSync } from "fs";
import { join, relative } from "path";

const ROOT = process.cwd();
const SCRIPTS_DIR = join(ROOT, "scripts");
const OUTPUT = join(ROOT, "docs/inventory/SCRIPTS.md");

type Category = "archive-delete" | "promote-feature" | "promote-test" | "promote-npm-script" | "keep-as-is";

type Row = { path: string; sizeBytes: number; firstLine: string; category: Category; rationale: string };

function classify(absPath: string, content: string): { category: Category; rationale: string } {
  const name = absPath.split(/[\\/]/).pop()!.toLowerCase();
  const head = content.slice(0, 500).toLowerCase();

  // Inventory scripts (this script's siblings) are ongoing tooling
  if (name.startsWith("inventory/") || absPath.includes("/inventory/")) {
    return { category: "keep-as-is", rationale: "Phase 1 inventory tool, ongoing" };
  }

  // Seed scripts — genuine ops tools
  if (name.startsWith("seed-") || head.includes("seed fixture") || head.includes("seed data")) {
    return { category: "keep-as-is", rationale: "Seed fixtures — ops tooling" };
  }

  // Verify / check scripts — usually pre-launch sanity, often promote to test
  if (/^verify-|^check-|^smoke/.test(name)) {
    return { category: "promote-test", rationale: "Verification logic better expressed as a Jest test" };
  }

  // Audit scripts — typically one-shot investigation
  if (/^audit-/.test(name)) {
    return { category: "archive-delete", rationale: "One-off audit — delete once findings actioned" };
  }

  // Inspect/diagnose scripts — usually one-shot
  if (/^inspect-|^diagnose-/.test(name)) {
    return { category: "archive-delete", rationale: "Diagnostic — delete once issue resolved" };
  }

  // Send-test / resend scripts — one-shot email tests
  if (/^send-test-|^resend-/.test(name)) {
    return { category: "archive-delete", rationale: "One-shot email test — delete once template verified" };
  }

  // Sweep/backfill scripts — usually one-shot data fixes
  if (/^sweep-|^backfill-|^fix-/.test(name)) {
    return { category: "archive-delete", rationale: "One-shot data fix — delete once applied" };
  }

  // Migrate / migration tools
  if (/^migrate-/.test(name)) {
    return { category: "promote-feature", rationale: "Migration logic might belong in an admin action" };
  }

  // One-off explicitly tagged
  if (/^one-off-|^retro-/.test(name)) {
    return { category: "archive-delete", rationale: "Tagged as one-off — delete once superseded" };
  }

  // Build / render / export tooling
  if (/^build-|^render-|^export-|^generate-/.test(name)) {
    return { category: "promote-npm-script", rationale: "Build/generate tool — move to package.json scripts" };
  }

  // Health / metric reports
  if (/^health-|^demo-/.test(name)) {
    return { category: "keep-as-is", rationale: "Recurring health/demo report" };
  }

  // Append / persona / setup / rehearsal — case by case
  if (/^append-|^persona-|^setup-|^rehearsal-/.test(name)) {
    return { category: "archive-delete", rationale: "Setup or persona-specific — likely stale" };
  }

  return { category: "keep-as-is", rationale: "Manual review required" };
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(ts|mjs|js|cjs)$/.test(entry)) out.push(full);
  }
  return out;
}

function emit(rows: Row[]) {
  const byCategory = new Map<Category, Row[]>();
  for (const r of rows) {
    const arr = byCategory.get(r.category) ?? [];
    arr.push(r);
    byCategory.set(r.category, arr);
  }

  const order: Category[] = ["archive-delete", "promote-feature", "promote-test", "promote-npm-script", "keep-as-is"];
  const counts = order.map((c) => `${c}=${(byCategory.get(c) ?? []).length}`).join("  ");

  const lines: string[] = [
    "# Scripts Census",
    "",
    `Generated by [scripts/inventory/scripts.ts](../../scripts/inventory/scripts.ts). Last run: ${new Date().toISOString().slice(0, 10)}.`,
    "",
    "Powers the [BUILD_PLAN Phase 4 scripts cull](../BUILD_PLAN.md#phase-4--scripts-cull-interleaved-from-week-8). Target: ≤ 15 files post-cull.",
    "",
    "Classifications are **heuristic** based on filename patterns. Each script needs manual review before deletion or promotion.",
    "",
    "## Summary",
    "",
    `- **Total scripts:** ${rows.length}`,
    `- **Target:** ≤ 15 (Law 15 + Phase 4 cull)`,
    `- **Heuristic breakdown:** ${counts}`,
    "",
    "---",
    "",
  ];

  for (const cat of order) {
    const group = byCategory.get(cat) ?? [];
    lines.push(`## ${cat} (${group.length})`, "");
    if (group.length === 0) { lines.push("_(none)_", ""); continue; }
    lines.push("| Script | Rationale (heuristic) |", "|---|---|");
    for (const r of group.sort((a, b) => a.path.localeCompare(b.path))) {
      lines.push(`| \`${r.path}\` | ${r.rationale} |`);
    }
    lines.push("");
  }

  lines.push("---", "", "## Footnotes", "", "- Re-run: `npx tsx scripts/inventory/scripts.ts`", `- Last updated: ${new Date().toISOString().slice(0, 10)}`);

  writeFileSync(OUTPUT, lines.join("\n"));
  console.log(`Wrote ${OUTPUT}`);
  console.log(`  ${counts}`);
}

const files = walk(SCRIPTS_DIR);
const rows: Row[] = files.map((abs) => {
  const rel = relative(ROOT, abs).replace(/\\/g, "/");
  const stat = statSync(abs);
  let content = "";
  try { content = readFileSync(abs, "utf8"); } catch { /* skip */ }
  const firstLine = (content.split("\n")[0] || "").slice(0, 80);
  const { category, rationale } = classify(rel, content);
  return { path: rel, sizeBytes: stat.size, firstLine, category, rationale };
});
emit(rows);
