// Walks app/ for page.tsx files and lists every route with audience role
// and rough remediation complexity score.
//
// Output: docs/inventory/SURFACES.md.
//
// Re-run with: `npx tsx scripts/inventory/surfaces.ts`
//
// Registered in docs/SCRIPTS_REGISTRY.md per Law 15. Lifetime: ongoing.
import { readdirSync, statSync, writeFileSync, readFileSync } from "fs";
import { join, relative } from "path";

const ROOT = process.cwd();
const APP_DIR = join(ROOT, "app");
const OUTPUT = join(ROOT, "docs/inventory/SURFACES.md");

type Surface = {
  route: string;
  audience: "agent" | "internal" | "command" | "portal" | "marketing" | "auth" | "other";
  complexity: "S" | "M" | "L"; // rough scoring based on file size + import count
  hasLayout: boolean;
  fileSize: number;
  importCount: number;
};

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (entry === "page.tsx") out.push(full);
  }
  return out;
}

function routeFromPath(abs: string): string {
  const rel = relative(APP_DIR, abs).replace(/\\/g, "/").replace(/\/page\.tsx$/, "");
  // Strip route groups like (protected) from display
  return "/" + rel.replace(/\([^)]+\)\//g, "");
}

function audienceFor(route: string): Surface["audience"] {
  if (route.startsWith("/agent/")) return "agent";
  if (route.startsWith("/dashboard")) return "internal";
  if (route.startsWith("/command")) return "command";
  if (route.startsWith("/portal/")) return "portal";
  if (route.startsWith("/login") || route.startsWith("/forgot") || route.startsWith("/claim")) return "auth";
  if (route === "/" || route.startsWith("/cookie") || route.startsWith("/billing-terms")) return "marketing";
  return "other";
}

function complexityFor(fileSize: number, importCount: number): "S" | "M" | "L" {
  if (fileSize > 12_000 || importCount > 25) return "L";
  if (fileSize > 4_000 || importCount > 10) return "M";
  return "S";
}

function emit(rows: Surface[]) {
  // Group by audience
  const byAudience = new Map<string, Surface[]>();
  for (const r of rows) {
    const arr = byAudience.get(r.audience) ?? [];
    arr.push(r);
    byAudience.set(r.audience, arr);
  }

  const order: Surface["audience"][] = ["agent", "internal", "command", "portal", "auth", "marketing", "other"];

  const lines: string[] = [
    "# Surfaces Census",
    "",
    `Generated by [scripts/inventory/surfaces.ts](../../scripts/inventory/surfaces.ts). Last run: ${new Date().toISOString().slice(0, 10)}.`,
    "",
    "Powers the [BUILD_PLAN Phase 3 surface queue](../BUILD_PLAN.md#phase-3--surface-remediation-weeks-10-26).",
    "",
    "## Summary",
    "",
    `- **Total routes:** ${rows.length}`,
    `- **Complexity:** S=${rows.filter(r => r.complexity === "S").length}, M=${rows.filter(r => r.complexity === "M").length}, L=${rows.filter(r => r.complexity === "L").length}`,
    "",
    "Complexity score is heuristic (file size + import count). Real remediation cost depends on the surface's data dependencies and number of states.",
    "",
    "---",
    "",
  ];

  for (const audience of order) {
    const group = byAudience.get(audience) ?? [];
    if (group.length === 0) continue;
    lines.push(`## ${audience} (${group.length} routes)`, "");
    lines.push("| Route | Complexity | File size | Imports |", "|---|---|---|---|");
    for (const r of group.sort((a, b) => a.route.localeCompare(b.route))) {
      lines.push(`| \`${r.route}\` | ${r.complexity} | ${Math.round(r.fileSize / 100) / 10}KB | ${r.importCount} |`);
    }
    lines.push("");
  }

  lines.push("---", "", "## Footnotes", "", "- Re-run: `npx tsx scripts/inventory/surfaces.ts`", `- Last updated: ${new Date().toISOString().slice(0, 10)}`);

  writeFileSync(OUTPUT, lines.join("\n"));
  console.log(`Wrote ${OUTPUT}`);
  console.log(`  total=${rows.length}`);
}

const files = walk(APP_DIR);
const rows: Surface[] = files.map((abs) => {
  const route = routeFromPath(abs);
  const audience = audienceFor(route);
  const stat = statSync(abs);
  let content = "";
  try { content = readFileSync(abs, "utf8"); } catch { /* skip */ }
  const importCount = (content.match(/^import /gm) || []).length;
  return {
    route,
    audience,
    fileSize: stat.size,
    importCount,
    hasLayout: false,
    complexity: complexityFor(stat.size, importCount),
  };
});
emit(rows);
